### ISSUE TITLE
Data has no peers and does not have a backup url

### ISSUE THREAD

**Issue by ieee8023** [mila-iqia/gene-graph-conv#1]
I think add a URL right into the .get call in the code so that it can skip the torrent if there are no peers.

Torrent is here: http://academictorrents.com/details/ae2691e4f4f068d32f83797b224eb854b27bd3ee

**Comment by mweiss17** [comment]
I changed the torrent and have it hosted with a backup: http://academictorrents.com/details/2b7e470d87a017be3826ef6ec55893f3a61f5af7

We can discuss modifications to the AT python client over there
