### ISSUE TITLE
README guide should say dataframe instead of networkx graph for neighborhood

### ISSUE THREAD

**Issue by mdanb** [mila-iqia/gene-graph-conv#29]
Thanks for this great work! I could be wrong, but I believe the README guide should say that the `neighborhood` should be a dataframe containing the adjacency matrix rather than a networkX graph. The following line in the file `gcn.py` in the function `setup_layers` was causing issues otherwise:
        ```self.adj = scipy.sparse.csr_matrix(self.adj)```

**Comment by mweiss17** [comment]
Hmm. As far as I can make it, as long as you're putting in a 2d matrix scipy is happy:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

Happy to review any PRs to make the README easier though!
