### ISSUE TITLE
Pytorch version used

### ISSUE THREAD

**Issue by mdanb** [mila-iqia/gene-graph-conv#30]
What pytorch version was used for this code? I'm asking because the line 
```x = SparseMM(D)(x.t()).t()```
in the function `_adj_mul` in `gcn_layers` is giving me:
```
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```

**Comment by mweiss17** [comment]
Hi there -- I believe this was pytorch 0.4, but I will try to take a look at the dependencies and see if I can update things, or at least make it more clear. Will keep you posted.

**Comment by mdanb** [comment]
Awesome thank you! Also, as another possibility (if anyone is interested), I ended up just changing the line to `x = torch.matmul(D, torch.transpose(x, 1, 0))`

**Comment by mweiss17** [comment]
Great. I've taken a look and it seems like this actually works fine with torch 1.8 if you make a change kind of like that one. I've create a PR here: https://github.com/mila-iqia/gene-graph-conv/pull/32
