### ISSUE TITLE
cannot download data

### ISSUE THREAD

**Issue by xzwang313** [mila-iqia/gene-graph-conv#33]
I run clinical-task-hpsearch.py and tried to download data from https://tcga.xenahubs.net/download/TCGA.ACC.sampleMap/ACC_clinicalMatrix.gz

It failed each time and got error message: urllib.error.HTTPError: HTTP Error 403: Forbidden

What can I do to download the data?

Thanks!

**Comment by ieee8023** [comment]
I found my old project folder and committed the clinical matrix data to the repo https://github.com/mila-iqia/gene-graph-conv/tree/master/meta_dataloader/data 

Let me know if anything else is missing!
